FROM alpine:3.19

RUN apk add --no-cache \
    python3 \
    && rm -rf /var/cache/apk/*

WORKDIR /app
COPY watch_containers.py /app/

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["python3 /app/watch_containers.py"]

